#!/bin/bash

function readContent()
{
    content=$(< ".disco.history" )
}

function isInHistory()
{
    readContent

    if [[ $content == *"$1"* ]]; then
        return 0
    fi

    content="$content $trim_title"

     echo "$content" > ".disco.history"

    return 1
}

function findMeAPage()
{
	location=$(curl -Ls -o /dev/null -w %{url_effective} https://en.wikipedia.org/wiki/Special:Random)

title=$(curl -Ls "$location"| grep \<title\>|sed "s/\<title\>\([^<]*\).*/\1/")

trim_title=${title%" - Wikipedia, the free encyclopedia"}

echo "

Look what I found! $trim_title!! Sounds Fascinating"
echo "Should we keep looking?[y/N]"
read keeplooking

if [ $keeplooking == "y" ]; then
	findMeAPage
else
    if  ! isInHistory $trim_title ; then
	    open $location
    else
        findMeAPage
    fi
fi

}

findMeAPage




